openapi: 3.0.2
info:
  description: "This is the API descriotion for the ZON-App (iOS and Android)"
  version: "0.1.0"
  title: "ZON App API"
  termsOfService: "write me"
  contact:
    email: "internet-technik@zeit.de"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
servers: 
  - url: "https://app-api.zeit.de/v.0.1.0/"
    description: "Production API"
  - url: "https://app-api.staging.zeit.de/v.0.1.0/"
    description: "Staging API"
paths:
  /structure:
    get:
       tags:
         - "structure"
       summary: "Get all infos about the site's structure, e.g. tabs"
       responses:
         "200":
           description: "Sucessful operation"
           content:
             application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tab'
         "503":
           description: "Server Timeout"
         "403":
           description: "Access Forbidden"
components:
  schemas:
    Tab:
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
          example: 10
  securitySchemes:
    zon_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://oauth.zeit.de/oauth/authorize'
          scopes:
            'read:all': read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header
